class ProbSeq {
    public:
    short pos[4];
    short selected = 0;
    short probs[4][64];
    bool patt[4][64];
    short clockDiv[4][64];
    short clockDivCount[4];
    short lengthMin[4] = {0,0,0,0};
    short lengthMax[4] = {15,15,15,15};
    short clockDivOp;
    short clockDivision = 2;
    short lengthMinTemp = 0;
    bool lengthSet = 0;
    short prob = 5;
    short set = 0;
    short morph = 0;
    short division = 0;
    bool view = 0;
    short follow = 0;
    short temp = 0;
    short posNote[4];
    short note[4][64];
    bool activeNote[4][64];
    bool selParam = 0;
    short timeParam = 0;
    short eventParam = 0;

    void run();
    void clock();
    void updatePosition();
    void writeNewPosition();
    void pattMorph();
    void output();
    void controls();
    void drawBg();
    void drawMatrix();
    void drawMatrixLED();
    void drawKey(int key);
    void setStep(int key);
    void drawInfo();
    void drawDivision();
    void drawControls();
    void followPos();
};