class ProbSeq {
    public:
    short menu = 0;
    bool view = 0;
    bool follow = 0;
    short set = 0;
    short channel = 0;
    short division = 0;
    short pos[4];
    short probs[4][64];
    bool patt[4][64];
    short clockDiv[4][64];
    short clockDivCount[4];
    short lengthMin[4] = {0,0,0,0};
    short lengthMax[4] = {15,15,15,15};
    short clockDivOp;
    short clockDivision = 2;
    short lengthMinTemp = 0;
    bool lengthSet = 1;
    short prob = 5;
    short morph = 0;
    short temp = 0;
    short posNote[4];
    short note[4][64];
    bool selParam = 0;
    short timeParam = 0;
    short eventParam = 0;
    short timeMenuParam = 0;
    short eventMenuParam = 0;
    short eventMode[4] = {0,0,0,0};
    short eventStep[4] = {0,0,0,0};
    String eventModeName[2] = {"Probability","Markov Chain"};
    String eventStepName[2] = {"Sync","Trig"};
    short eventSetProbMin = 0;
    short eventSetProbMax = 96;
    short eventPos[4];
    bool eventActiveNote[4][16];
    short eventProbSetNote = 0;
    short eventProbNotes[4][16];
    short eventProbMorph[4] = {0,0,0,0};
    short eventProbMin[4][16];
    short eventProbMax[4][16];

    void run();
    void clock();
    void updatePosition();
    void writeNewPosition();
    void pattMorph();
    void output();
    void controls();
    void drawBg();
    void drawMatrix();
    void drawMatrixLED();
    void drawKey(int key);
    void setStep(int key);
    void drawInfo();
    void drawDivision();
    void drawControls();
    void followPos();
    void drawParams();
    void drawMenu();
};